### ISSUE TITLE
Unusual install behaviour

### ISSUE THREAD

**Issue by johnkeates** [Enrise/elasticsearch-formula#2]
I recently noticed some unusual behaviour, when setting up ES on a fresh Ubuntu 14.04.02 LTS VM, the pkg requirement for "default-jre-headless" wasn't found. It's in the repo, and I could manually install it, but afterwards, the requisites not found issue still popped up. By commenting out

require:
  pkg: default-jre-headless

in install.sls, it worked. It seems that somehow, the minion wasn't able to find or resolve the dependency. As a test, I removed default-jre-headless and elasticsearch, and did a new highstate with the pkg requirement commented out, and it resolved all by itself.

If there is no reason other than 'completeness' for that pkg to be required, I'd like to remove it (and put in a PR).

**Comment by syphernl** [comment]
This is actually by-design and mentioned in the readme:

```
Include "elasticsearch" in your project for the "full stack". Optionally you can select which states you require. If you don't have java running yet, you can include "elasticsearch.java"
```

In Salt a `pkg`-dependency actually refers to the `pkg.*` state with a given ID within Salt, not to the actual package itself on the system. Even though the package may exist, if the id within Salt does not this indeed results in an error.

So you'll need to include it in your top-file as:

```
- elasticsearch.java
- elasticsearch
```

In some Salt setups the JRE dependency may already be available (e.g. in a base setup before it hits this formula) which then would result in duplicate declarations, causing the highstate to fail.

Even though JRE is required by Elasticsearch neither the package in the official Ubuntu repo nor the one in the Elasticsearch-repo have a dependency for it.

An alternative could be a pillar setting `install_jre:True` but this makes it less flexible since this approach allows you to override the id and specify a specific version. 

In Ubuntu the `default-jre-headless` is a pseudopackage for `openjdk-7-jre-headless` but perhaps there you'd like (or need) to use `openjdk-8-jre-headless` instead?

I hope this clears things up!

**Comment by johnkeates** [comment]
The issue isn't as much dependency management, but Salt not being able to satisfy the dependency. APT doesn't seem to have any problem with it, but when installed in a state, it doesn't work. (Salt presents with a non-critical error, elasticsearch doesn't get installed)

**Comment by edwardsmit** [comment]
@johnkeates I can't reproduce your problem on Ubuntu 14.04.2 LTS. With and without the require elasticsearch installed and ran.
However I think it would be preferable to have a require check for a valid java environment, which would enable a choice for the actual java-environment.

**Comment by johnkeates** [comment]
I'll spin up a fresh VM and try to reproduce it.
